name : Alien-CPP-cpanm

on: push

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install alien
        run: curl -L https://cpanmin.us | perl - --configure-timeout=1920 Alien-*.tar.gz -v
